

# Configuration file. Edit the options below

doc_dir: "/Users/oparcollet/SCRADOC" # The directory where to write the doc.
#doc_dir: "web/_pages/doc" # The directory where to write the doc.
sources:      # A list of the sources to be parsed
  - src/nda.hpp

skip_deprecated: true
source_file_only: false # Document only functions/classes/... in the source file, excluding indirect includes
compile_examples: false # Compile the example to check them.

#source_prefix:  /Users/oparcollet/Dropbox (Simons Foundation)/src/demo # A prefix to remove from the source files
source_prefix:  /Users/oparcollet/Dropbox (Simons Foundation)/src/nda/c++ # A prefix to remove from the source files

includers:     # regex -> filename
  '.*': nda/nda.hpp

# include_dirs:          # Include dirs ?
# system_include_dirs:   #  A list of includes
# cxxflags:              # e.g. "-std=c++17 -DCPP2DOC=1 "


#white_list: ['nda::for_\w*']  
white_list: ['nda::\w*']  
black_list: ['nda::expr.*', '.*_impl'] 

# source_root:  
# source_remote_prefix: # https://github.com/TRIQS/triqs/blob/2.2.x/


